apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev
  description: dev
spec:
  type: department
  # Intentional no profile for testing
  parent: evermos
  children: [brandops, rex, cf]
