apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops
  description: evermos infra de
spec:
  type: department
  # Intentional no profile for testing
  parent: evermos
  children: [evermos, everpro]
